version: "3.7"

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: yabinadmin
      MONGO_INITDB_ROOT_PASSWORD: asecurepasswordhere


  yabin:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - mongo